---
extends: eslint-config-shakacode/base

globals:
  __DEBUG__: true

env:
  jest: true
  browser: true

parser: babel-eslint
rules:
  react/jsx-filename-extension:
    - extensions:
      - .js
      - .jsx
settings:
  import/resolver:
    node:
      paths:
      - example/app/startup
      - example/app/components/Content
      - example/app/components/Hero
      - example/app/layout
