---
extends: eslint-config-shakacode/base
rules:
  import/no-unresolved: off

globals:
  __DEBUG__: true

env:
  jest: true

parser: "@babel/eslint-parser"

parserOptions:
  requireConfigFile: false
  babelOptions:
    parserOpts:
      plugins:
        - jsx
