---
# This needs to be commented to avoid conflict with the same config in the example app
# extends: eslint-config-shakacode/base

rules:
  import/no-unresolved: off

globals:
  __DEBUG__: true

env:
  jest: true

parser: "@babel/eslint-parser"

parserOptions:
  requireConfigFile: false
  babelOptions:
    parserOpts:
      plugins:
        - jsx
